In [3]:
import pandas as pd

In [4]:
file_path = "data/phenotype.csv"
df = pd.read_csv(file_path)

/var/folders/7k/xvqgnqvn78d16vz2xqslqmxc0000gn/T/ipykernel_18304/4109111359.py:2: DtypeWarning: Columns (0: qualifier, 1: onset, 2: sex, 3: modifier) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

In [6]:
df

,database_id,disease_name,qualifier,hpo_id,reference,evidence,onset,frequency,sex,modifier,aspect,biocuration
0,OMIM:619340,Developmental and epileptic encephalopathy 96,NaN,HP:0011097,PMID:31675180,PCS,NaN,1/2,NaN,NaN,P,HPO:probinson[2021-06-21]
1,OMIM:619340,Developmental and epileptic encephalopathy 96,NaN,HP:0002187,PMID:31675180,PCS,NaN,1/1,NaN,NaN,P,HPO:probinson[2021-06-21]
2,OMIM:619340,Developmental and epileptic encephalopathy 96,NaN,HP:0001518,PMID:31675180,PCS,NaN,1/2,NaN,NaN,P,HPO:probinson[2021-06-21]
3,OMIM:619340,Developmental and epileptic encephalopathy 96,NaN,HP:0032792,PMID:31675180,PCS,NaN,1/2,NaN,NaN,P,HPO:probinson[2021-06-21]
4,OMIM:619340,Developmental and epileptic encephalopathy 96,NaN,HP:0011451,PMID:31675180,PCS,NaN,1/2,NaN,NaN,P,HPO:probinson[2021-06-21]
...,...,...,...,...,...,...,...,...,...,...,...,...
285593,ORPHA:1777,Temtamy syndrome,NaN,HP:0000324,ORPHA:1777,TAS,NaN,HP:0040283,NaN,NaN,P,ORPHA:orphadata[2026-06-23]
285594,ORPHA:1777,Temtamy syndrome,NaN,HP:0000506,ORPHA:1777,TAS,NaN,HP:0040283,NaN,NaN,P,ORPHA:orphadata[2026-06-23]
285595,ORPHA:1777,Temtamy syndrome,NaN,HP:0000568,ORPHA:1777,TAS,NaN,HP:0040283,NaN,NaN,P,ORPHA:orphadata[2026-06-23]
285596,ORPHA:1777,Temtamy syndrome,NaN,HP:0004209,ORPHA:1777,TAS,NaN,HP:0040283,NaN,NaN,P,ORPHA:orphadata[2026-06-23]
285597,ORPHA:1777,Temtamy syndrome,NaN,HP:0001382,ORPHA:1777,TAS,NaN,HP:0040283,NaN,NaN,P,ORPHA:orphadata[2026-06-23]

In [8]:
df.shape

(285598, 12)

In [10]:
df.head()

,database_id,disease_name,qualifier,hpo_id,reference,evidence,onset,frequency,sex,modifier,aspect,biocuration
0,OMIM:619340,Developmental and epileptic encephalopathy 96,NaN,HP:0011097,PMID:31675180,PCS,NaN,1/2,NaN,NaN,P,HPO:probinson[2021-06-21]
1,OMIM:619340,Developmental and epileptic encephalopathy 96,NaN,HP:0002187,PMID:31675180,PCS,NaN,1/1,NaN,NaN,P,HPO:probinson[2021-06-21]
2,OMIM:619340,Developmental and epileptic encephalopathy 96,NaN,HP:0001518,PMID:31675180,PCS,NaN,1/2,NaN,NaN,P,HPO:probinson[2021-06-21]
3,OMIM:619340,Developmental and epileptic encephalopathy 96,NaN,HP:0032792,PMID:31675180,PCS,NaN,1/2,NaN,NaN,P,HPO:probinson[2021-06-21]
4,OMIM:619340,Developmental and epileptic encephalopathy 96,NaN,HP:0011451,PMID:31675180,PCS,NaN,1/2,NaN,NaN,P,HPO:probinson[2021-06-21]

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 285598 entries, 0 to 285597
Data columns (total 12 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   database_id   285598 non-null  str
 1   disease_name  285598 non-null  str
 2   qualifier     727 non-null     str
 3   hpo_id        285598 non-null  str
 4   reference     285598 non-null  str
 5   evidence      285598 non-null  str
 6   onset         3052 non-null    str
 7   frequency     221921 non-null  str
 8   sex           640 non-null     str
 9   modifier      1028 non-null    str
 10  aspect        285598 non-null  str
 11  biocuration   285598 non-null  str
dtypes: str(12)
memory usage: 26.1 MB

In [14]:
df.describe()

,database_id,disease_name,qualifier,hpo_id,reference,evidence,onset,frequency,sex,modifier,aspect,biocuration
count,285598,285598,727,285598,285598,285598,3052,221921,640,1028,285598,285598
unique,12956,12534,1,11645,22735,3,17,2332,4,54,5,12060
top,OMIM:618505,Sotos syndrome,NOT,HP:0000007,ISBN-13:978-0721606156,TAS,HP:0003577,HP:0040283,MALE,HP:0012825,P,ORPHA:orphadata[2026-06-23]
freq,234,245,727,4288,230,136275,892,45216,448,360,267782,115875

In [17]:
df.isnull().sum()

database_id          0
disease_name         0
qualifier       284871
hpo_id               0
reference            0
evidence             0
onset           282546
frequency        63677
sex             284958
modifier        284570
aspect               0
biocuration          0
dtype: int64

In [19]:
df.isnull().mean() * 100

database_id      0.000000
disease_name     0.000000
qualifier       99.745446
hpo_id           0.000000
reference        0.000000
evidence         0.000000
onset           98.931365
frequency       22.296024
sex             99.775909
modifier        99.640054
aspect           0.000000
biocuration      0.000000
dtype: float64

In [21]:
df.duplicated().sum()

np.int64(32)